### ISSUE TITLE
unable to install skopeo

### ISSUE THREAD

**Issue by mathewkoshy493** [runcom/skopeo#7]
I am getting the following error while installing skopeo

inspect.go:8:2: cannot find package "github.com/runcom/skopeo/docker" in any of:
    /home/mathew/go/src/github.com/skopeo/vendor/github.com/runcom/skopeo/docker (vendor tree)
    /home/mathew/golang/goroot/go/src/github.com/runcom/skopeo/docker (from $GOROOT)
    /home/mathew/go/src/github.com/runcom/skopeo/docker (from $GOPATH)
inspect.go:9:2: cannot find package "github.com/runcom/skopeo/types" in any of:
    /home/mathew/go/src/github.com/skopeo/vendor/github.com/runcom/skopeo/types (vendor tree)
    /home/mathew/golang/goroot/go/src/github.com/runcom/skopeo/types (from $GOROOT)
    /home/mathew/go/src/github.com/runcom/skopeo/types (from $GOPATH)

I followed these steps while installing
1)cd $GOPATH/src/github.com
2)git clone https://github.com/runcom/skopeo
3)cd runcom && make binary

**Comment by runcom** [comment]
Wrong, you need to create "runcom" directory after github.com and then clone skopeo inside so the path would be gopath/src/github.com/runcom/skopeo

**Comment by runcom** [comment]
I'll update the Readme cause ive just noticed the building section is wrong. Thanks!!

**Comment by runcom** [comment]
@mathewkoshy493 fixed in master
